name: knowledge-graph-predict
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - scikit-learn
  - torch-scatter
  - ordered_set=4.1.0
  - pip
